version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: root
  MYSQL_DATABASE: vintages_bases
  REACT_APP_SERVER_PORT: 3000

services:
  mysql-db:
    # platform: linux/amd64 #! docker pull --platform linux/x86_64 mysql
    platform: linux/x86_64/v8 #! docker pull --platform linux/x86_64 mysql
    # image: mysql:8 #! ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
    image: mysql:5.7 #! ERROR: no matching manifest for linux/arm64/v8 in the manifest list entries
    # image: mariadb

    container_name: mysql_container_toumaivintage
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT: root
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./back/src/Model/vintages_bases.sql:/docker-entrypoint-initdb.d/vintages_bases.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container_toumaivintage
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  back:
    build: ./back
    container_name: backend_container_toumaivintage
    # image: node:19
    depends_on:
      - mysql-db
    environment:
      <<: *common-variables
      MYSQL_HOST_IP: mysql-db
    ports:
      - 3000:3000
    volumes:
      - ./back:src/AppToumaiVintage
    links:
      - mysql-db
    command: npm start
  front:
    build: ./front
    # dockerfile: Dockerfile.dev
    # working_dir: /app
    container_name: frontend_container_toumaivintage
    # image: node:19
    environment:
      <<: *common-variables
      NODE_PATH: src
    ports:
      - 5173:5173
    volumes:
      - ./front:/App
    links:
      - back
    command: npm start
    # command: sh -c "npm install && npm start"