FROM node:19 AS build
WORKDIR /back
COPY package.json .
RUN npm install
COPY ..
RUN npm run build

# FROM nginx
# COPY --from=build /client/build /usr/share/nginx/html
# FROM vite
# COPY --from=build /front/build