const products2 =    [
    {
      id: 1,
      title: "Labtop",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "70 €",    
      imgSrc: "../src/media/images/ordinateur.jpg",
      category: "Ordinateurs",
    },
    {
      id: 2,
      title: "Labtopoda",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "78 €",    
      imgSrc: "../src/media/images/ordinateur.jpg",
      category: "Ordinateurs",
    },
    {
      id: 3,
      title: "Chaine hihi 400",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "150 €",    
      imgSrc: "../src/media/images/telephone.jpg",
      category: "Téléphones",
    },
    {
      id: 4,
      title: "Photo 888",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "800 €",    
      imgSrc: "../src/media/images/son-accessoires.jpg",
      category: "Sons et Accessoires",
    },
    {
      id: 5,
      title: "Jeu nint",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "80 €",    
      // imgSrc: "../src/media/images/Categorie_JeuxVeosVintages.png",
      imgSrc: "../src/media/images/jeu-vidéo.jpg",
      category: "jeux vidéo",
    },
    {
      id: 6,
      title: "Nokia 5522",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "50 €",    
      imgSrc: "../src/media/images/appareil-photo.jpg",
      category: "Appareils Photo",
    },
    {
      id: 7,
      title: "Labtop",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "70 €",    
      imgSrc: "../src/media/images/ordinateur.jpg",
      category: "Ordinateurs",
    },
    {
      id: 8,
      title: "Labtop",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "70 €",    
      imgSrc: "../src/media/images/ordinateur.jpg",
      category: "Ordinateurs",
    },
    {
      id: 9,
      title: "Labtop",
      description: "Thundercats iPhone mumblecore selvage raw denim slow-carb leggings gochujang helvetica man braid jianbing. Marfa vaporware",
      price: "70 €",    
      imgSrc: "../src/media/images/ordinateur.jpg",
      category: "Ordinateurs",
    },
  ]
  
  export default products2